---
require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/ClassStructure:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - spec/**/*
