---
require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-sorbet

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/ClassStructure:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Sorbet/StrictSigil:
  Enabled: true
