---
require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sorbet

AllCops:
  NewCops: enable

Metrics:
  Enabled: false

# https://github.com/sorbet/sorbet/issues/6832
Naming/BlockForwarding:
  Enabled: false

Style/Documentation:
  Enabled: false
